[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd frontend && pnpm install"]

[phases.build]
cmds = ["cd frontend && pnpm build"]

[start]
cmd = "cd frontend && pnpm start"
